# Generated by Django 5.0.6 on 2024-05-17 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_details',
        ),
    ]
