# Generated by Django 5.0.6 on 2024-05-17 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0004_rename_email_user_details_ids'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_details',
        ),
    ]
